In [3]:
import pandas as pd
import numpy as np
df = pd.read_csv('../Spaceship_Titanic/train.csv')

In [4]:
# 表示数の調整
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 30)

In [5]:
df.head(2)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True

In [6]:
df.tail(2)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
8691,9280_01,Europa,False,E/608/S,55 Cancri e,32.0,False,0.0,1049.0,0.0,353.0,3235.0,Celeon Hontichre,False
8692,9280_02,Europa,False,E/608/S,TRAPPIST-1e,44.0,False,126.0,4688.0,0.0,0.0,12.0,Propsh Hontichre,True

In [7]:
df.index

RangeIndex(start=0, stop=8693, step=1)

In [8]:
df.columns

Index(['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age',
       'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck',
       'Name', 'Transported'],
      dtype='str')

In [9]:
df.describe()

,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck
count,8514.000000,8512.000000,8510.000000,8485.000000,8510.000000,8505.000000
mean,28.827930,224.687617,458.077203,173.729169,311.138778,304.854791
std,14.489021,666.717663,1611.489240,604.696458,1136.705535,1145.717189
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,19.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,27.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,38.000000,47.000000,76.000000,27.000000,59.000000,46.000000
max,79.000000,14327.000000,29813.000000,23492.000000,22408.000000,24133.000000

In [18]:
df.T.head()

                    0            1            2            3            4     \
PassengerId      0001_01      0002_01      0003_01      0003_02      0004_01
HomePlanet        Europa        Earth       Europa       Europa        Earth
CryoSleep          False        False        False        False        False
Cabin              B/0/P        F/0/S        A/0/S        A/0/S        F/1/S
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                      5            6            7            8     \
PassengerId        0005_01      0006_01      0006_02      0007_01
HomePlanet           Earth        Earth        Earth        Earth
CryoSleep            False        False         True        False
Cabin                F/0/P        F/2/S        G/0/S        F/3/S
Destination  PSO J318.5-22  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    9            10           11           12           13    \
PassengerId      0008_01      0008_02      0008_03      0009_01      0010_01
HomePlanet        Europa       Europa       Europa         Mars        Earth
CryoSleep           True         True        False        False        False
Cabin              B/1/P        B/1/P        B/1/P        F/1/P        G/1/S
Destination  55 Cancri e  TRAPPIST-1e  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e

                    14           15           16           17           18    \
PassengerId      0011_01      0012_01      0014_01      0015_01      0016_01
HomePlanet         Earth        Earth         Mars        Earth         Mars
CryoSleep          False        False        False        False         True
Cabin              F/2/P          NaN        F/3/P        F/4/P        F/5/P
Destination  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e  55 Cancri e  TRAPPIST-1e

                    19           20           21           22           23    \
PassengerId      0017_01      0017_02      0020_01      0020_02      0020_03
HomePlanet         Earth        Earth        Earth        Earth        Earth
CryoSleep          False        False         True         True         True
Cabin              G/0/P        F/6/P        E/0/S        E/0/S        E/0/S
Destination  TRAPPIST-1e  55 Cancri e  TRAPPIST-1e  55 Cancri e  55 Cancri e

                    24             25           26           27    \
PassengerId      0020_04        0020_05      0020_06      0022_01
HomePlanet         Earth          Earth        Earth         Mars
CryoSleep          False           True        False        False
Cabin              E/0/S          E/0/S        E/0/S        D/0/P
Destination  TRAPPIST-1e  PSO J318.5-22  TRAPPIST-1e  TRAPPIST-1e

                    28           29           30           31           32    \
PassengerId      0024_01      0025_01      0026_01      0028_01      0030_01
HomePlanet        Europa        Earth       Europa         Mars        Earth
CryoSleep           True        False        False        False        False
Cabin              C/2/S        F/6/S        C/0/P        F/8/P        G/4/S
Destination  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e

                    33           34           35           36           37    \
PassengerId      0031_01      0031_02      0031_03      0034_01      0035_01
HomePlanet          Mars         Mars         Mars       Europa         Mars
CryoSleep          False        False        False         True        False
Cabin              F/9/P        F/9/P        F/9/P        D/1/S        D/1/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e  55 Cancri e

                    38           39           40           41           42    \
PassengerId      0036_01      0038_01      0039_01      0041_01      0043_01
HomePlanet         Earth        Earth        Earth        Earth       Europa
CryoSleep          False        False         True         True        False
Cabin              F/8/S       F/10/S        G/1/P        G/2/P        B/3/P
Destination  55 Cancri e  55 Cancri e  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e

                    43           44             45           46       47    \
PassengerId      0044_01      0044_02        0044_03      0045_01  0045_02
HomePlanet         Earth        Earth          Earth         Mars     Mars
CryoSleep           True         True           True        False     True
Cabin              G/3/P        G/3/P          G/3/P       F/10/P   F/10/P
Destination  TRAPPIST-1e  55 Cancri e  PSO J318.5-22  TRAPPIST-1e      NaN

                    48           49           50           51           52    \
PassengerId      0050_01      0051_01      0052_01      0053_01      0056_01
HomePlanet         Earth        Earth        Earth        Earth       Europa
CryoSleep          False        False        False        False        False
Cabin              E/1/S        E/2/S        G/6/S       F/11/S        A/1/S
Destination  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    53           54             55           56    \
PassengerId      0056_02      0056_03        0058_01      0061_01
HomePlanet        Europa       Europa          Earth        Earth
CryoSleep           True        False           True        False
Cabin              A/1/S        A/1/S          G/7/S       F/12/S
Destination  TRAPPIST-1e  TRAPPIST-1e  PSO J318.5-22  TRAPPIST-1e

                    57           58           59           60    \
PassengerId      0062_01      0064_01      0064_02      0066_01
HomePlanet         Earth         Mars          NaN        Earth
CryoSleep          False         True         True        False
Cabin             F/13/S       F/14/S        E/3/S        G/6/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                      61           62           63           64    \
PassengerId        0067_01      0067_02      0067_03      0068_01
HomePlanet           Earth        Earth        Earth         Mars
CryoSleep             True        False        False        False
Cabin               G/10/S       G/10/S       F/15/S        E/4/S
Destination  PSO J318.5-22  TRAPPIST-1e  55 Cancri e  TRAPPIST-1e

                    65           66           67           68    \
PassengerId      0069_01      0070_01      0071_01      0072_01
HomePlanet         Earth        Earth        Earth        Earth
CryoSleep          False        False        False        False
Cabin             F/16/S       F/13/P       F/14/P       F/17/S
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                      69           70           71           72    \
PassengerId        0073_01      0074_01      0076_01      0077_01
HomePlanet            Mars       Europa         Mars         Mars
CryoSleep            False        False        False        False
Cabin                D/3/P        C/3/S       F/18/S       F/15/P
Destination  PSO J318.5-22  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    73           74           75           76           77    \
PassengerId      0078_01      0081_01      0082_01      0082_02      0082_03
HomePlanet        Europa        Earth         Mars         Mars         Mars
CryoSleep          False         True        False         True        False
Cabin              C/4/S       G/13/S       F/16/P       F/16/P       F/16/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    78           79           80             81    \
PassengerId      0084_01      0085_01      0086_01        0088_01
HomePlanet         Earth       Europa        Earth           Mars
CryoSleep          False         True        False           True
Cabin             G/14/S        C/5/S       F/17/P          E/5/S
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  PSO J318.5-22

                    82           83           84           85           86    \
PassengerId      0090_01      0091_01      0091_02      0092_01      0092_02
HomePlanet         Earth        Earth        Earth        Earth        Earth
CryoSleep           True         True        False        False         True
Cabin             G/15/S       G/16/S       F/20/S        G/9/P        G/9/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    87           88           89           90    \
PassengerId      0092_03      0097_01      0098_01      0098_02
HomePlanet         Earth       Europa        Earth        Earth
CryoSleep           True        False        False        False
Cabin              G/9/P        A/2/S       G/11/P       G/11/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                      91           92           93           94    \
PassengerId        0099_01      0099_02      0101_01      0102_01
HomePlanet           Earth        Earth         Mars        Earth
CryoSleep            False          NaN         True        False
Cabin               F/19/P       G/12/P          NaN       F/23/S
Destination  PSO J318.5-22  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    95           96           97           98           99    \
PassengerId      0103_01      0103_02      0103_03      0105_01      0107_01
HomePlanet         Earth        Earth        Earth        Earth         Mars
CryoSleep          False         True         True          NaN        False
Cabin             F/24/S       G/18/S       G/18/S       F/21/P        D/2/S
Destination  TRAPPIST-1e  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    100          101          102          103          104   \
PassengerId      0108_01      0108_02      0108_03      0110_01      0110_02
HomePlanet         Earth        Earth        Earth       Europa       Europa
CryoSleep           True        False        False        False          NaN
Cabin             G/19/S       G/19/S       G/19/S          NaN        B/5/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    105          106          107          108          109   \
PassengerId      0110_03      0110_04      0111_01      0112_01      0113_01
HomePlanet        Europa       Europa       Europa       Europa        Earth
CryoSleep          False         True         True        False        False
Cabin              B/5/P        B/5/P        E/6/S        B/1/S       F/23/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e  TRAPPIST-1e

                    110          111          112          113          114   \
PassengerId      0114_01      0115_01      0116_01      0119_01      0119_02
HomePlanet         Earth         Mars       Europa          NaN       Europa
CryoSleep          False          NaN        False        False         True
Cabin             G/20/S       F/24/P        D/4/P        A/0/P        A/0/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    115          116          117          118          119   \
PassengerId      0120_01      0122_01      0123_01      0126_01      0127_01
HomePlanet          Mars        Earth        Earth         Mars         Mars
CryoSleep           True        False        False         True        False
Cabin             F/25/P       G/21/S       F/27/P       F/27/S        E/7/S
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    120          121            122          123   \
PassengerId      0128_01      0128_02        0129_01      0133_01
HomePlanet          Mars         Mars          Earth         Mars
CryoSleep          False        False           True         True
Cabin              D/3/S        E/8/S         G/22/S       F/29/S
Destination  TRAPPIST-1e  TRAPPIST-1e  PSO J318.5-22  TRAPPIST-1e

                    124          125            126          127      128   \
PassengerId      0133_02      0134_01        0136_01      0138_01  0138_02
HomePlanet          Mars        Earth          Earth        Earth    Earth
CryoSleep          False        False          False         True    False
Cabin              D/5/S       G/17/P         G/23/S       G/18/P    E/5/P
Destination  TRAPPIST-1e  TRAPPIST-1e  PSO J318.5-22  TRAPPIST-1e      NaN

                    129          130          131          132          133   \
PassengerId      0139_01      0140_01      0140_02      0141_01      0144_01
HomePlanet        Europa        Earth        Earth         Mars        Earth
CryoSleep           True         True        False        False        False
Cabin              C/6/S       G/19/P       F/29/P       F/30/P       F/31/S
Destination  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    134          135          136          137          138   \
PassengerId      0146_01      0147_01      0148_01      0149_01      0151_01
HomePlanet         Earth        Earth         Mars        Earth        Earth
CryoSleep          False         True        False         True         True
Cabin             G/25/S       G/26/S       F/31/P       G/27/S       G/20/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e  55 Cancri e

                139          140          141          142          143   \
PassengerId  0152_01      0160_01      0163_01      0163_02      0164_01
HomePlanet     Earth        Earth       Europa       Europa        Earth
CryoSleep      False        False         True         True        False
Cabin         F/32/P       G/22/P        B/8/P        B/8/P       G/28/S
Destination      NaN  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                      144          145          146          147   \
PassengerId        0164_02      0165_01      0167_01      0167_02
HomePlanet           Earth         Mars         Mars         Mars
CryoSleep             True         True         True        False
Cabin               G/28/S       F/37/P       F/35/S       F/35/S
Destination  PSO J318.5-22  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    148          149            150          151   \
PassengerId      0169_01      0170_01        0171_01      0172_01
HomePlanet         Earth        Earth          Earth        Earth
CryoSleep           True        False           True         True
Cabin             G/23/P       E/10/S         G/30/S       G/24/P
Destination  TRAPPIST-1e  TRAPPIST-1e  PSO J318.5-22  TRAPPIST-1e

                    152          153          154          155          156   \
PassengerId      0173_01      0174_01      0177_01      0178_01      0179_01
HomePlanet         Earth        Earth       Europa         Mars        Earth
CryoSleep            NaN        False        False        False        False
Cabin             E/11/S       F/38/P        B/2/S        D/6/S       G/26/P
Destination  TRAPPIST-1e  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    157          158          159          160          161   \
PassengerId      0179_02      0179_03      0181_01      0182_01      0183_01
HomePlanet         Earth        Earth        Earth       Europa        Earth
CryoSleep          False        False        False         True        False
Cabin             G/26/P       G/26/P       G/27/P        C/3/P       F/36/S
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    162          163          164          165          166   \
PassengerId      0186_01      0188_01      0189_01      0190_01      0192_01
HomePlanet         Earth        Earth        Earth        Earth        Earth
CryoSleep          False         True        False         True         True
Cabin             G/28/P       G/31/S        E/8/P       G/32/S       G/29/P
Destination  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e  55 Cancri e  TRAPPIST-1e

                    167          168          169          170          171   \
PassengerId      0192_02      0192_03      0193_01      0193_02      0193_03
HomePlanet         Earth        Earth         Mars         Mars         Mars
CryoSleep          False        False         True        False        False
Cabin             G/29/P       G/29/P       F/41/P       F/41/P       F/41/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    172            173          174            175   \
PassengerId      0195_01        0196_01      0197_01        0198_01
HomePlanet          Mars           Mars       Europa          Earth
CryoSleep          False          False        False            NaN
Cabin             F/42/P          D/5/P        C/5/P         G/30/P
Destination  TRAPPIST-1e  PSO J318.5-22  TRAPPIST-1e  PSO J318.5-22

                    176          177          178          179          180   \
PassengerId      0199_01      0200_01      0201_01      0201_02      0202_01
HomePlanet         Earth        Earth       Europa       Europa       Europa
CryoSleep           True         True         True         True         True
Cabin             G/33/S       G/31/P        B/3/S        B/3/S        B/9/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e

                    181          182          183          184   \
PassengerId      0202_02      0203_01      0205_01      0206_01
HomePlanet        Europa       Europa        Earth       Europa
CryoSleep          False         True        False        False
Cabin              A/2/P        C/8/S       G/34/S        C/9/S
Destination  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e

                      185          186          187          188   \
PassengerId        0207_01      0210_01      0211_01      0211_02
HomePlanet           Earth          NaN         Mars         Mars
CryoSleep             True         True        False         True
Cabin               G/32/P        D/6/P       F/44/P       F/44/P
Destination  PSO J318.5-22  55 Cancri e  TRAPPIST-1e  TRAPPIST-1e

                    189          190          191          192          193   \
PassengerId      0211_03      0212_01      0212_02      0213_01      0216_01
HomePlanet          Mars        Earth        Earth        Earth        Earth
CryoSleep          False        False        False        False        False
Cabin             F/44/P        E/9/P       F/45/P       F/46/P       F/40/S
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e

                    194          195          196          197          198   \
PassengerId      0217_01      0219_01      0220_01      0220_02      0220_03
HomePlanet         Earth        Earth        Earth        Earth        Earth
CryoSleep          False         True         True        False         True
Cabin             F/47/P       G/36/P       G/37/P       G/37/P       G/37/P
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    199          200          201          202          203   \
PassengerId      0220_04      0220_05      0220_06      0220_07      0221_01
HomePlanet         Earth        Earth        Earth        Earth         Mars
CryoSleep          False        False        False         True        False
Cabin             E/10/P       F/48/P       G/37/P       G/37/P       E/13/S
Destination  TRAPPIST-1e  TRAPPIST-1e  55 Cancri e  TRAPPIST-1e  55 Cancri e

                    204          205          206          207          208   \
PassengerId      0221_02      0221_03      0221_04      0221_05      0221_06
HomePlanet          Mars         Mars         Mars         Mars         Mars
CryoSleep          False        False         True        False        False
Cabin             E/13/S       E/13/S       E/13/S       E/13/S       E/13/S
Destination  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e  TRAPPIST-1e

                    209          210          211          212          213   \
PassengerId      0221_07      0222_01      0222_02      0222_03      0223_01

In [17]:
df.sort_index(axis = 1, ascending = False).head(2)

,VRDeck,VIP,Transported,Spa,ShoppingMall,RoomService,PassengerId,Name,HomePlanet,FoodCourt,Destination,CryoSleep,Cabin,Age
0,0.0,False,False,0.0,0.0,0.0,0001_01,Maham Ofracculy,Europa,0.0,TRAPPIST-1e,False,B/0/P,39.0
1,44.0,False,True,549.0,25.0,109.0,0002_01,Juanna Vines,Earth,9.0,TRAPPIST-1e,False,F/0/S,24.0

In [16]:
df.sort_values(by=['Age','VIP'],ascending=False).head(2)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
338,0378_03,Europa,False,B/11/S,TRAPPIST-1e,79.0,False,5649.0,235.0,7.0,2579.0,2175.0,Naslon Pirejus,False
615,0642_03,Europa,False,C/25/S,TRAPPIST-1e,79.0,False,0.0,0.0,0.0,2210.0,2.0,Chabik Kiling,False

In [20]:
df['Age'].head(2)

0    39.0
1    24.0
Name: Age, dtype: float64

In [22]:
df.Age.head(2)

0    39.0
1    24.0
Name: Age, dtype: float64

In [24]:
df[['Age','VIP']].head()

    Age    VIP
0  39.0  False
1  24.0  False
2  58.0   True
3  33.0  False
4  16.0  False

In [25]:
df[0:3]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False

In [34]:
df.loc[0]

PassengerId             0001_01
HomePlanet               Europa
CryoSleep                 False
Cabin                     B/0/P
Destination         TRAPPIST-1e
Age                        39.0
VIP                       False
RoomService                 0.0
FoodCourt                   0.0
ShoppingMall                0.0
Spa                         0.0
VRDeck                      0.0
Name            Maham Ofracculy
Transported               False
Name: 0, dtype: object

In [36]:
df.loc[:,["Age","VIP"]][0:3]

    Age    VIP
0  39.0  False
1  24.0  False
2  58.0   True

In [37]:
df.loc[0:3,["Age","VIP"]]

    Age    VIP
0  39.0  False
1  24.0  False
2  58.0   True
3  33.0  False

In [38]:
df.loc[1,"Age"]

np.float64(24.0)

In [40]:
df.iloc[3][0:3]

PassengerId    0003_02
HomePlanet      Europa
CryoSleep        False
Name: 3, dtype: object

In [41]:
df.iloc[3:5,0:2]

  PassengerId HomePlanet
3     0003_02     Europa
4     0004_01      Earth

In [43]:
df.iloc[[1,2,4],[0,2]]

  PassengerId CryoSleep
1     0002_01     False
2     0003_01     False
4     0004_01     False

In [44]:
df.iloc[1:3,:]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False

In [46]:
df.iloc[:,1:3][0:2]

  HomePlanet CryoSleep
0     Europa     False
1      Earth     False

In [47]:
df.iloc[1,1]

'Earth'

In [49]:
df[df["Age"]>20][0:2]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True

In [52]:
df[df["Age"].isin([24,26])][0:2]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
6,0006_01,Earth,False,F/2/S,TRAPPIST-1e,26.0,False,42.0,1539.0,3.0,0.0,0.0,Billex Jacostaffey,True

In [54]:
df.dropna(how="any")[0:2]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True

In [56]:
df.fillna(value = 5)[0:2]

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True

In [57]:
pd.isna(df)

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8688,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8689,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8690,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8691,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8692,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [62]:
df_num = df.select_dtypes(include= "number").columns
df_obj = df.select_dtypes(include= "object").columns

C:\Users\user\AppData\Local\Temp\ipykernel_9540\1495057071.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df_obj = df.select_dtypes(include= "object").columns

In [63]:
df[df_num].mean()

Age              28.827930
RoomService     224.687617
FoodCourt       458.077203
ShoppingMall    173.729169
Spa             311.138778
VRDeck          304.854791
dtype: float64

In [64]:
df[df_num].agg(lambda x: np.mean(x) * 2)

Age              57.655861
RoomService     449.375235
FoodCourt       916.154407
ShoppingMall    347.458338
Spa             622.277556
VRDeck          609.709583
dtype: float64

In [65]:
df[df_num].transform(lambda x: x * 2)

        Age  RoomService  FoodCourt  ShoppingMall      Spa  VRDeck
0      78.0          0.0        0.0           0.0      0.0     0.0
1      48.0        218.0       18.0          50.0   1098.0    88.0
2     116.0         86.0     7152.0           0.0  13430.0    98.0
3      66.0          0.0     2566.0         742.0   6658.0   386.0
4      32.0        606.0      140.0         302.0   1130.0     4.0
...     ...          ...        ...           ...      ...     ...
8688   82.0          0.0    13638.0           0.0   3286.0   148.0
8689   36.0          0.0        0.0           0.0      0.0     0.0
8690   52.0          0.0        0.0        3744.0      2.0     0.0
8691   64.0          0.0     2098.0           0.0    706.0  6470.0
8692   88.0        252.0     9376.0           0.0      0.0    24.0

[8693 rows x 6 columns]

In [69]:
df.groupby("Transported")[["Age"]].mean()

                   Age
Transported
False        29.922858
True         27.748834

In [70]:
df.stack()

0     PassengerId              0001_01
      HomePlanet                Europa
      CryoSleep                  False
      Cabin                      B/0/P
      Destination          TRAPPIST-1e
                            ...
8692  ShoppingMall                 0.0
      Spa                          0.0
      VRDeck                      12.0
      Name            Propsh Hontichre
      Transported                 True
Length: 121702, dtype: object

In [76]:
pd.pivot_table(df,values="Age",index="Transported",columns="VIP",aggfunc=["mean","median"])

                  mean            median
VIP              False      True   False True
Transported
False        29.683383  38.221311   27.0  34.0
True         27.621990  36.210526   26.0  32.5